export const data = [
  {
    name: "Mixmax",
    budget_name: "Software subscription",
    owner_id: 1,
    spent: {
      value: 100,
      currency: "SGD",
    },
    available_to_spend: {
      value: 1000,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "9 Feb",
    limit: 100,
    status: "active",
  },
  {
    name: "Quickbooks",
    budget_name: "Software subscription",
    owner_id: 2,
    spent: {
      value: 50,
      currency: "SGD",
    },
    available_to_spend: {
      value: 250,
      currency: "SGD",
    },
    card_type: "subscription",
    limit: 10,
    status: "active",
  },
  {
    name: "Slack",
    budget_name: "Software subscription",
    owner_id: 1,
    spent: {
      value: 75,
      currency: "SGD",
    },
    available_to_spend: {
      value: 500,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "15 Mar",
    limit: 150,
    status: "active",
  },
  {
    name: "Netflix",
    budget_name: "Entertainment",
    owner_id: 2,
    spent: {
      value: 20,
      currency: "SGD",
    },
    available_to_spend: {
      value: 200,
      currency: "SGD",
    },
    card_type: "subscription",
    limit: 50,
    status: "active",
  },
  {
    name: "Zoom",
    budget_name: "Communication",
    owner_id: 1,
    spent: {
      value: 40,
      currency: "SGD",
    },
    available_to_spend: {
      value: 300,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "22 May",
    limit: 80,
    status: "active",
  },
  {
    name: "Adobe Creative Cloud",
    budget_name: "Software subscription",
    owner_id: 2,
    spent: {
      value: 80,
      currency: "SGD",
    },
    available_to_spend: {
      value: 400,
      currency: "SGD",
    },
    card_type: "subscription",
    limit: 100,
    status: "active",
  },
  {
    name: "Spotify",
    budget_name: "Entertainment",
    owner_id: 1,
    spent: {
      value: 15,
      currency: "SGD",
    },
    available_to_spend: {
      value: 100,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "12 Apr",
    limit: 30,
    status: "active",
  },
  {
    name: "Amazon Web Services",
    budget_name: "Cloud Services",
    owner_id: 2,
    spent: {
      value: 120,
      currency: "SGD",
    },
    available_to_spend: {
      value: 800,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "18 Jul",
    limit: 200,
    status: "active",
  },
  {
    name: "Microsoft 365",
    budget_name: "Software subscription",
    owner_id: 9,
    spent: {
      value: 60,
      currency: "SGD",
    },
    available_to_spend: {
      value: 300,
      currency: "SGD",
    },
    card_type: "subscription",
    limit: 80,
    status: "active",
  },
  {
    name: "Google Workspace",
    budget_name: "Software subscription",
    owner_id: 1,
    spent: {
      value: 50,
      currency: "SGD",
    },
    available_to_spend: {
      value: 200,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "30 Sep",
    limit: 100,
    status: "active",
  },
  {
    name: "Salesforce",
    budget_name: "CRM",
    owner_id: 2,
    spent: {
      value: 90,
      currency: "SGD",
    },
    available_to_spend: {
      value: 400,
      currency: "SGD",
    },
    card_type: "subscription",
    limit: 120,
    status: "active",
  },
  {
    name: "Trello",
    budget_name: "Project Management",
    owner_id: 1,
    spent: {
      value: 30,
      currency: "SGD",
    },
    available_to_spend: {
      value: 150,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "14 Nov",
    limit: 60,
    status: "active",
  },
  {
    name: "Dropbox",
    budget_name: "Cloud Storage",
    owner_id: 2,
    spent: {
      value: 25,
      currency: "SGD",
    },
    available_to_spend: {
      value: 100,
      currency: "SGD",
    },
    card_type: "burner",
    expiry: "8 Dec",
    limit: 50,
    status: "active",
  },
  {
    name: "Mailchimp",
    budget_name: "Email Marketing",
    owner_id: 1,
    spent: {
      value: 70,
      currency: "SGD",
    },
    available_to_spend: {
      value: 200,
      currency: "SGD",
    },
    card_type: "subscription",
    limit: 90,
    status: "active",
  },
  {
    name: "HubSpot",
    budget_name: "CRM",
    owner_id: 1,
    spent: {
      value: 110,
      currency: "SGD",
    },
    available_to_spend: {
      value: 500,
      currency: "SGD",
    },
    card_type: "subscription",
    limit: 150,
    status: "active",
  },
];
